### ISSUE TITLE
Add AWS S3 driver test

### ISSUE THREAD

**Issue by inakianduaga** [inakianduaga/eloquent-external-storage#20]

**Comment by inakianduaga** [comment]
# General guideline for setup

http://milesj.me/blog/read/amazon-s3-testing-travis-ci

# TODO
- [x] Add dotenv php as a dev dependency, configure test credentials to be read from environment (locally use `.env` file, travis ci uses travis.yml encrypted variables.
- [x] Create S3 user and setup bucket permissions for testing
- [x] Encrypt Aws S3 credentials 
  use travis ruby gem or https://www.npmjs.com/package/travis-encrypt
- [x] Write tests
